if (Meteor.isServer) {
    Meteor.startup(function () {
        Tracks.remove({});

        var i
          , x = Config.viewpoint.spawnX
          , z = Config.viewpoint.spawnZ + 10 // we start a little South of the spawn-point, and head Southwards from there
          , turn = Math.random() * 2 * Math.PI
          , start = x + 'x' + z // @todo append '/a', '/b/', if this user already has a track starting at these coords
          , xmin = 99999
          , xmax = -99999
          , zmin = 99999
          , zmax = -99999
          , markers = []
        ;

        //// The first time the app starts, generate an initial sample Track and record it into the `Tracks` collection.
        if ( 0 !== Tracks.find().count() ) {
// console.log( '# Tracks: ' + Tracks.find().count() );
        } else {
            console.log('The ‘Tracks’ collection is empty...');

            //// Create a Track with eight markers.
            for (i=8; i>0; i--) {

                //// Add the marker, which is either the 'start' marker, or a marker which uses values generated during the previous `for ...` step.
                markers.push ( (i % 4) + 1 + ' ' + x + ' ' + z + ' ' + turn ); // space-delimited marker type (`1|2|3|4`), x-position, z-position, and turn-angle

                //// Semi-randomize the x-position, z-position and turn-angle, ready for the next `for ...` step.
                x += Math.round( Math.random() * 10 - 5 ); // veer East and West
                z += Math.round( Math.random() * 10     ); // always head South
                turn = Math.random() * 2 * Math.PI;

                //// Each ‘Track’ contains boundary markers, which help speed up searches for nearby Tracks.
                xmin = Math.min(xmin, x);
                xmax = Math.max(xmax, x);
                zmin = Math.min(zmin, z);
                zmax = Math.max(zmax, z);
            }

console.log(-2,xmin,xmax,zmin,zmax,markers);

            //// Record to the `Tracks` collection.
            Tracks.insert({
                user:    -2 // signifies generated by the server
              , markers: markers
              , start:   start
              , xmin:    xmin
              , xmax:    xmax
              , zmin:    zmin
              , zmax:    zmax
            });

        }
    });
}
